POST http://localhost:5000/register
Content-Type: application/json

{
 
"user_name":"nyhgvhgt", 
"first_name":"hfybh", 
"last_name":"hnfgy", 
"email":"uuyghvbhjyuh56n@gmail.com", 
"password":"ygu5r675q#",  
"isAdmin":0
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
   "email":"retdwsd46n@gmail.com",
    "password":"ygu5r675q#"
}
###
PUT http://localhost:5000/user/updateUserProfile
Content-Type: application/json

{
 
"user_name":"peter",  
"email":"jp@gmail.com", 
"password":"poiuywq#",  
}
###
GET http://localhost:5000/users
###
