POST http://localhost:5000/register
Content-Type: application/json

{
 
"user_name":"KgVintonJr",
"first_name":"Viton",
"last_name":"Junour",
"email":"vintongakajuniour@gmail.com",
"password":"qwerty1234",
"isAdmin":0 
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"vintonmogakajuniour@gmail.com",
    "password":"qwerty1234"
}
###
POST http://localhost:5000/updateUserProfile
Content-Type: application/json

{
 
"user_name":"peter",  
"email":"jp@gmail.com", 
"password":"poiuywq#",  
}
###
GET http://localhost:5000/users
###
