POST http://localhost:5000/register
Content-Type: application/json

{
 
"user_name":"peterjohn", 
"first_name":"peter", 
"last_name":"john", 
"email":"johnp@gmail.com", 
"password":"poiuytrewq#",  
"isAdmin":1
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"vinton@gmail.com",
    "password":"zxcvbnm098765"
}
###
POST http://localhost:5000/updateUserProfile
Content-Type: application/json

{
 
"user_name":"peter",  
"email":"jp@gmail.com", 
"password":"poiuywq#",  
}
###
